# -*- coding: utf-8 -*-
"""
Visualization for the DDG K-surface pipeline on the Poincaré disk.

Provides one plotting class per pipeline stage:

    Pdisc_plot  — Chebyshev net on the Poincaré disk (matplotlib)
    Arc_plot    — Chebyshev net on the unit sphere (PyVista)
    Surf_plot   — embedded surface in R³ (PyVista)

Author: Ari Bormanis
"""

import os
import matplotlib.pyplot as plt
import numpy as np
import pyvista as pv
                    
                    
class Surf_create:
    """
    Create a mesh for the R³ surface generated by the Lelieuvre map applied to the branched
    Chebyshev net on the sphere.
    """
    def __init__(self, surf_grid):
        self.grid = surf_grid.grid
        
        
    def sector_mesh(self, surf_grid):
        pass
        

    def create_pt_ar(self, surf_grid):
        """Return a list of all non-NaN vertex positions in surf_grid."""
        pts = []
        for i in range(surf_grid.rows):
            for j in range(surf_grid.cols):
                r = surf_grid.grid[i, j, :]
                if not np.any(np.isnan(r)):
                    pts.append(r)
        return pts

    def create_pt_map(self, surf_grid):
        """Return a dict mapping each non-NaN vertex (by bytes key) to its index in create_pt_ar."""
        pt_map = {}
        n = 0
        for i in range(surf_grid.rows):
            for j in range(surf_grid.cols):
                r = surf_grid.grid[i, j, :]
                if not np.any(np.isnan(r)):
                    pt_map[r.tobytes()] = n
                    n += 1
        return pt_map

    def create_mesh(self, surf_grid, depth=0):
        """Build a pyvista PolyData mesh from surf_grid quads"""
        verts = self.create_pt_ar(surf_grid)
        pt_map = self.create_pt_map(surf_grid)

        faces = []
        grid = surf_grid.grid

        for i in range(surf_grid.rows - 1):
            for j in range(surf_grid.cols - 1):
                r0  = grid[i,   j,   :]
                r1  = grid[i,   j+1, :]
                r2  = grid[i+1, j,   :]
                r12 = grid[i+1, j+1, :]

                if not (np.any(np.isnan(r0)) or np.any(np.isnan(r1)) or
                        np.any(np.isnan(r2)) or np.any(np.isnan(r12))):
                    faces.append([4, pt_map[r0.tobytes()], pt_map[r1.tobytes()],
                                  pt_map[r12.tobytes()], pt_map[r2.tobytes()]])

        self.pl.add_mesh(pv.PolyData(verts, faces))

        if surf_grid.children is not None:
            self.poly_plot(surf_grid.children[2], depth=depth+1)
            self.poly_plot(surf_grid.children[0], depth=depth+1)
            self.poly_plot(surf_grid.children[1], depth=depth+1)